---
version: 2.1

orbs:
  terraform: feedyard/terraform@dev:latest

workflows:
  version: 2

  bootstrap-aws-key-value-store:
    jobs:
      - terraform/plan:
          name: plan-key-value-store
          context: infra-pipeline
          aws-role: AWS_ROLE_PROFILE
          aws-region: us-east-1
          encoded-file: environment.bin
          terraform-cloud-token: TERRAFORM_CLOUD_TOKEN
          working-directory: key-value-store
          env: profile

  # for use with bootstrap-cluster