---
version: 2.1

executors:

  bootstrap-cluster:
    working_directory: ~/aws-bootstrap
    docker:
    - image: quay.io/feedyard/circleci-infra-agent
    environment:
      BASH_ENV: local.env

commands:

  setup-job:
    steps:
    - checkout
    - setup_remote_docker
    - run:
        name: confirm Docker engine running
        command: docker info
    - run:
        name: decrypt secrets
        command: invoke dec

  setup-backend:
    parameters:
      account:
        description: 'short name used to identify aws account. e.g., sandbox, prod'
        type: string
    steps:
    - run:
        name: put parameter to stdout
        command: echo << parameters.account >>

jobs:

  terraform-plan:
    executor: bootstrap-cluster
    parameters:
      account:
        description: 'short name used to identify aws account. e.g., sandbox, prod'
        type: string
    steps:
      - setup-job
      - setup-backend:
          account: << parameters.account >>

workflows:
  aws-bootstrap-pipeline:
    jobs:
      - terraform-plan:
          account: 'first run account parameter'
      - terraform-plan:
          account: 'second run account parameter'
