---
version: 2.1

executors:

  bootstrap-cluster:
    working_directory: ~/aws-bootstrap
    docker:
    - image: quay.io/feedyard/circleci-infra-agent
    environment:
      BASH_ENV: local.env

commands:

  setup-job:
    steps:
    - checkout
    - setup_remote_docker
    - run:
        name: confirm Docker engine running
        command: docker info
    - run:
        name: decrypt secrets
        command: invoke dec

  setup-backend:
    parameters:
      account:
        description: 'short name used to identify aws account. e.g., sandbox, prod'
        type: string
    steps:
    - run:
        name: put parameter to stdout
        command: echo << parameters.account >>

jobs:

  terraform-plan:
    executor: bootstrap-cluster
    parameters:
      account:
        description: 'short name used to identify aws account. e.g., sandbox, prod'
        type: string
    steps:
      - setup-job
      - setup-backend:
          account: << parameters.account >>

    terraform-apply:
      executor: bootstrap-cluster
      parameters:
        account:
          description: 'short name used to identify aws account. e.g., sandbox, prod'
          type: string
      steps:
      - setup-job
      - setup-backend:
          account: << parameters.account >>

workflows:
  aws-bootstrap-cluster-pipeline:
    jobs:
      - terraform-plan:
          name: TEST plan
          account: 'terraform plan of bootstrap TEST cluster'
      - approve:
          name: TEST approve
          type: approval
          requires:
          - TEST plan
      - terraform-apply:
          name: TEST apply
          account: 'terraform apply to bootstrap TEST cluster'
          requires:
            - TEST approve
      - terraform-plan:
          name: RUN plan
          account: 'terraform plan of bootstrap RUN cluster'
          requires:
            - TEST apply
      - approve:
          name: RUN approve
          type: approval
          requires:
            - RUN plan
      - terraform-apply:
          name: RUN apply
          account: 'terraform apply to bootstrap RUN cluster'
          requires:
            - RUN approve
