---
version: 2.1

orbs:
  terraform: feedyard/terraform@dev:latest

workflows:
  version: 2

  bootstrap-aws-key-value-store:
    jobs:
      - terraform/aws:
          name: plan-key-value-store
          plan-step: true
          env: profile
          aws-role: $AWS_ROLE_PROFILE
          aws-region: us-east-1
          encoded-file: environment.bin
          use-provider-role: true
          terraform-cloud-token: $TERRAFORM_CLOUD_TOKEN
          context: infra-pipeline
          working-directory: key-value-store

  # for use with bootstrap-cluster