---
version: 2.1

executors:

  bootstrap-cluster:
    working_directory: ~/aws-bootstrap
    docker:
    - image: quay.io/feedyard/circleci-infra-agent
    environment:
      BASH_ENV: local.env

commands:

  setup-job:
    steps:
    - checkout
    - setup_remote_docker
    - run:
        name: confirm Docker engine running
        command: docker info
    - run:
        name: decrypt secrets
        command: invoke dec

  setup-backend:
    parameters:
      account:
        description: 'short name used to identify aws account. e.g., sandbox, prod'
        type: string
    steps:
    - run:
        name: put parameter to stdout
        command: echo << parameters.account >>

jobs:

  tf-plan:
    executor: bootstrap-cluster
    parameters:
      account:
        description: 'short name used to identify aws account. e.g., sandbox, prod'
        type: string
    steps:
      - setup-job
      - setup-backend:
          account: << parameters.account >>

workflows:
  aws-bootstrap-pipeline:
    jobs:
      - tf-plan:
          name: test-cluster plan
          account: 'terraform plan of test cluster'
      - approve-test-plan:
          type: approval
          requires:
          - test-cluster plan
      - tf-plan:
          name: test-cluster apply
          account: 'terraform apply to test cluster'
          requires:
            - approve-test-plan
      - tf-plan:
          name: bootstrap-cluster plan
          account: 'terraform plan of bootstrap cluster'
          requires:
            - test-cluster apply
      - approve-bootstrap-plan:
          type: approval
          requires:
            - bootstrap-cluster plan
      - tf-plan:
          name: bootstrap-cluster apply
          account: 'terraform apply to bootstrap cluster'
          requires:
            - approve-bootstrap-plan
