---
version: 2.1

executors:

  bootstrap-cluster:
    working_directory: ~/aws-bootstrap
    docker:
    - image: quay.io/feedyard/circleci-infra-agent
    environment:
      BASH_ENV: local.env
      PIPELINE: aws-bootstrap
      PREFIX: feedyard
      STATEFILE: bootstrap-cluster.state
      DEFAULT_ENV: test
      DEFAULT_ACCOUNT: sandbox
      DEFAULT_REGION: us-east-1
      DEFAULT_PROFILE: default

commands:

  setup-job:
    steps:
    - checkout
    - setup_remote_docker
    - run:
        name: confirm Docker engine running
        command: docker info
    - run:
        name: decrypt secrets
        command: invoke dec

  setup-backend:
    parameters:
      account:
        description: 's3 bucket name'
        type: string
        default: $DEFAULT_ACCOUNT
      env:
        description: 'infrastructure environment name'
        type: string
        default: $DEFAULT_ENV
      region:
        description: 'aws region'
        type: string
        default: $DEFAULT_REGION
      profile:
        description: '~/.aws/credentials profile to use. Credentials file setup separately'
        type: string
        default: $DEFAULT_PROFILE
    steps:
      - run:
          name: write terraform backend.conf
          working_directory: bootstrap-cluster
          command: bash setup_aws_backend.sh $PREFIX-<< parameters.account >>-tf-state $PIPELINE/<< parameters.env >>/$STATEFILE << parameters.region >> << parameters.profile >>
                   # by convention the terraform state file naming is bucket/pipeline/environment/filename.state
                   #
                   # bucket = $PREFIX-$AWS_ACCOUNT-tf-state
                   # repo-name = $PIPELINE
                   # filename = $STATEFILE.state

  setup-credentials:
    parameters:
      access-id:
        description: 'aws account access key id'
        type: string
      secret-key:
        description: 'aws secret access key'
        type: string
      assume-role:
        description: 'aws account role to assume'
        type: string
        default: 'none'
      region:
        description: 'aws region'
        type: string
        default: $DEFAULT_REGION
    steps:
      - run:
          name: write ~/.aws/credentials
          working_directory: bootstrap-cluster
          command: bash setup_aws_credentials.sh << parameters.access-id >> << parameters.secret-key >> << parameters.region >> << parameters.assume-role >>

jobs:

  terraform:
    executor: bootstrap-cluster
    parameters:
      plan:
        description: 'set true to run terraform plan'
        type: boolean
        default: false
      apply:
        description: 'set true to run terraform apply'
        type: boolean
        default: false
      account:
        description: 'short name used to identify aws account. e.g., sandbox, prod'
        type: string
        default: $DEFAULT_ACCOUNT
      env:
        description: 'infrastructure environment name'
        type: string
        default: $DEFAULT_ENV
      region:
        description: 'aws region'
        type: string
        default: $DEFAULT_REGION
      access-id:
        description: 'aws account access key id'
        type: string
      secret-key:
        description: 'aws secret access key'
        type: string
      assume-role:
        description: 'aws account role to assume'
        type: string
        default: 'none'
    steps:
      - setup-job
      - setup-backend:
          account: << parameters.account >>
          env: << parameters.env >>
          region: << parameters.region >>
      - setup-credentials:
          access-id: << parameters.access-id >>
          secret-key: << parameters.secret-key >>
          region: << parameters.region >>
          assume-role: << parameters.assume-role >>
      - when:
          condition: << parameters.plan >>
          steps:
            - run:
                name: terraform plan
                working_directory: bootstrap-cluster
                command: echo 'terraform plan'
      - when:
          condition: << parameters.apply >>
          steps:
            - run:
                name: terraform apply
                working_directory:  bootstrap-cluster
                command: echo 'terraform apply'

workflows:
  aws-bootstrap-pipeline:
    jobs:
      - terraform:
          name: plan of test environment
          plan: true
          env: test
          account: sandbox
          access-id: $FEEDYARD_SANDBOX_ACCESS_KEY_ID
          secret-key: $FEEDYARD_SANDBOX_SECRET_ACCESS_KEY
      - approve:
          name: approve plan of test environment
          type: approval
          requires:
          - plan of test environment
      - terraform:
          name: apply plan to test environment
          apply: true
          account: sandbox
          env: test
          access-id: $FEEDYARD_SANDBOX_ACCESS_KEY_ID
          secret-key: $FEEDYARD_SANDBOX_SECRET_ACCESS_KEY
          requires:
            - approve plan of test environment
      - terraform:
          name: plan of run environment
          plan: true
          account: sandbox
          env: run
          access-id: $FEEDYARD_SANDBOX_ACCESS_KEY_ID
          secret-key: $FEEDYARD_SANDBOX_SECRET_ACCESS_KEY
          requires:
            - apply plan to test environment
      - approve:
          name: approve plan of run environment
          type: approval
          requires:
            - plan of run environment
      - terraform:
          name: apply plan to run environment
          apply: true
          account: sandbox
          env: run
          access-id: $FEEDYARD_SANDBOX_ACCESS_KEY_ID
          secret-key: $FEEDYARD_SANDBOX_SECRET_ACCESS_KEY
          requires:
            - approve plan of run environment
