---
version: 2.1

executors:

  bootstrap-cluster:
    working_directory: ~/aws-bootstrap
    docker:
    - image: quay.io/feedyard/circleci-infra-agent
    environment:
      BASH_ENV: local.env

commands:

  setup-job:
    steps:
    - checkout
    - setup_remote_docker
    - run:
        name: confirm Docker engine running
        command: docker info
    - run:
        name: decrypt secrets
        command: invoke dec

  setup-backend:
    parameters:
      product:
        description: 'product or team name, prefix used to tag or identify aws resources'
        type: string
      account:
        description: 'short name used to identify aws account. e.g., sandbox, prod'
        type: string
      infra-environment:
        description: 'infrastructure environment name. e.g., cluster name'
        type: string
      region:
        description: 'aws-region'
        type: string
    steps:
      - run:
          name: write backend.conf file
          working_directory: ~/aws-bootstrap/bootstrap-cluster
          command: bash setup_backend.sh << parameters.product >> << parameters.account >> << parameters.region >> << parameters.infra-environment >>

  setup-credentials:
    parameters:
      region:
        description: 'aws-region'
        type: string
      aws-access-key-id:
        type: string
      aws-secret-access-key:
        type: string
      aws-role:
        description: 'aws role in sts format: '
        type: string
    steps:
    - run:
        name: write backend.conf file
        working_directory: ~/aws-bootstrap/bootstrap-cluster
        command: bash setup_credentials.sh << parameters.aws-access-key-id >> << parameters.aws-secret-access-key >> << parameters.region >> << parameters.aws-role >>

# 1 = aws access key id for the pipeline service account identity (required)
# 2 = aws secret access key for the pipeline service account identity (required)
# 3 = aws region (required)
# 4 = aws role to assume (optional)

jobs:

  terraform-plan:
    executor: bootstrap-cluster
    environment:
      BASH_ENV: local.env
      PRODUCT: feedyard
      BOOTSTRAP_REGION: us-west-1
    parameters:
      product:
        description: 'product or team name, prefix used to tag or identify aws resources'
        type: string
      account:
        description: 'short name used to identify aws account. e.g., sandbox, prod'
        type: string
      infra-environment:
        description: 'infrastructure environment name. e.g., cluster name'
        type: string
      region:
        description: 'aws-region'
        type: string
      aws-access-key-id:
        type: string
      aws-secret-access-key:
        type: string
      aws-role:
        description: 'aws role in sts format: '
        type: string
    steps:
      - setup-job
      - run:
          name: setup bash_env
          command: source $BASH_ENV
      - setup-backend:
          product: << parameters.product >>
          account: << parameters.account >>
          region: << parameters.region >>
          infra-environment: << parameters.infra-environment >>
      - setup-credentials:
          region: << parameters.region >>
          aws-access-key-id: << parameters.aws-access-key-id >>
          aws-secret-access-key: << parameters.aws-secret-access-key >>
          aws-role: << parameters.aws-role >>

workflows:
  aws-bootstrap-pipeline:
    jobs:
      - terraform-plan:
          product: $PRODUCT
          account: nonprod
          region: $BOOTSTRAP_REGION
          infra-environment: test
          aws-access-key-id: $FEEDYARD_NONPROD_ACCESS_KEY_ID
          aws-secret-access-key: $FEEDYARD_NONPROD_SECRET_ACCESS_KEY
          aws-role: none




#version: 2
#
#defaults: &defaults
#  working_directory: ~/aws-bootstrap/bootstrap-cluster
#  environment:
#    PRODUCT: feedyard
#    BASH_ENV: local.env
#  docker:
#  - image: quay.io/feedyard/circleci-infra-agent
#
#jobs:
#
#  plan_bootstrap-sandbox:
#    <<: *defaults
#    steps:
#    - checkout
#    - setup_remote_docker
#    - run:
#        name: confirm Docker engine running
#        command: docker info
#    - run:
#        name: decrypt secrets
#        command: invoke dec
#    - run:
#        name: setup terraform remote state backend configuration file
#        working_directory: ~/aws-bootstrap/bootstrap-cluster
#        environment:
#          ACCOUNT: sandbox
#          AWS_REGION: us-east-1
#        command: >
#          bash setup_backend.sh
#            PRODUCT
#            $ACCOUNT
#            $AWS_REGION
#    - run:
#        name: setup aws credentials
#        environment:
#          AWS_REGION: us-east-1
#        command: >
#          bash setup_credentials.sh
#            $FEEDYARD_SANDBOX_ACCESS_KEY_ID
#            $FEEDYARD_SANDBOX_SECRET_ACCESS_KEY
#            $AWS_REGION
#    - run:
#        name: initialize the terraform state backend
#        working_directory: ~/aws-bootstrap/bootstrap-cluster
#        command: invoke init
#    - run:
#        name: generate terraform plan
#        working_directory: ~/aws-bootstrap/bootstrap-cluster
#        environment:
#          ACCOUNT: sandbox
#        command: invoke plan $ACCOUNT
#
#  apply_bootstrap_sandbox:
#    <<: *defaults
#    steps:
#    - checkout
#    - setup_remote_docker
#    - run:
#        name: confirm Docker
#        command: docker info
#    - run:
#        name: decrypt secrets
#        command: invoke dec
#    - run:
#        name: setup aws credentials
#        environment:
#          AWS_REGION: us-east-1
#        command: >
#          bash setup_credentials.sh
#          $FEEDYARD_PROFILE_ACCESS_KEY_ID
#          $FEEDYARD_PROFILE_SECRET_ACCESS_KEY
#          $AWS_REGION
#    - run:
#        name: setup terraform state file location
#        working_directory: ~/aws-bootstrap/secure-state-storage
#        environment:
#          AWS_REGION: us-east-1
#          ACCOUNT: prod
#        command: >
#          bash setup_backend.sh
#          $ORGANIZATION
#          $ACCOUNT
#          $AWS_REGION
#    - run:
#        name: initialize the terraform state backend
#        working_directory: ~/aws-bootstrap/secure-state-storage
#        command: invoke init
#    - run:
#        name: apply terraform plan
#        working_directory: ~/aws-bootstrap/secure-state-storage
#        environment:
#          ACCOUNT: prod
#        command: invoke apply $ACCOUNT
#    - run:
#        name: test terraform state
#        environment:
#          AWS_REGION: us-east-1
#          ACCOUNT: prod
#        command: invoke test $ACCOUNT
#
#
#workflows:
#  version: 2
#  di-baseline-platform-aws-resources-pipeline:
#    jobs:
#    - plan_preview
#    - approve-preview-plan:
#        type: approval
#        requires:
#        - plan_preview
#    - apply_preview:
#        requires:
#        - approve-preview-plan
#    - plan_nonprod:
#        requires:
#        - apply_preview
#    - approve-nonprod-plan:
#        type: approval
#        requires:
#        - plan_nonprod
#    - apply_nonprod:
#        requires:
#        - approve-nonprod-plan