---
version: 2.1

executors:

  bootstrap-cluster:
    working_directory: ~/aws-bootstrap
    docker:
    - image: quay.io/feedyard/circleci-infra-agent
    environment:
      PIPELINE: aws-bootstrap
      PREFIX: feedyard
      STATEFILE: bootstrap-cluster.state
      DEFAULT_ENV: test
      DEFAULT_ACCOUNT: sandbox
      DEFAULT_REGION: us-east-1
      DEFAULT_PROFILE: default
      BASH_ENV: local.env

commands:

  setup-job:
    steps:
    - checkout
    - setup_remote_docker
    - run:
        name: confirm Docker engine running
        command: docker info
    - run:
        name: decrypt secrets
        command: invoke dec

  # input params
  # 1 = s3 bucket name, this version of the script imposes the '-tf-state' name ending requirement
  # 2 = bucket key, or folder path and filename for tf state file
  # 3 = aws region
  # 4 = ~/.aws/credentials profile to use

  # by convention the terraform state file naming is bucket/pipeline/environment/filename.state
  #
  # bucket = $PREFIX-$AWS_ACCOUNT-tf-state
  # repo-name = $PIPELINE
  # filename = $STATEFILE.state
  setup-backend:
    parameters:
      account:
        description: 's3 bucket name'
        type: string
        default: $DEFAULT_ACCOUNT
      env:
        description: 'infrastructure environment name'
        type: string
        default: $DEFAULT_ENV
      region:
        description: 'aws region'
        type: string
        default: $DEFAULT_REGION
      profile:
        description: '~/.aws/credentials profile to use. Credentials file setup separately'
        type: string
        default: $DEFAULT_PROFILE
    steps:
    - run:
        name: put parameter to stdout
        command: bash setup_aws_backend.sh "$PREFIX-<< parameters.account >>-tf-state" "$PIPELINE/<< parameters.env >>/$STATEFILE" << parameters.region >> << parameters.profile >>

jobs:

  terraform-plan:
    executor: bootstrap-cluster
    parameters:
      account:
        description: 'short name used to identify aws account. e.g., sandbox, prod'
        type: string
        default: $DEFAULT_ACCOUNT
      env:
        description: 'infrastructure environment name'
        type: string
        default: $DEFAULT_ENV
      region:
        description: 'aws region'
        type: string
        default: $DEFAULT_REGION
    steps:
      - setup-job
      - setup-backend:
          account: << parameters.account >>
          env: << parameters.env >>
          region: << parameters.region >>

  terraform-apply:
    executor: bootstrap-cluster
    parameters:
      account:
        description: 'short name used to identify aws account. e.g., sandbox, prod'
        type: string
        default: $DEFAULT_ACCOUNT
      env:
        description: 'infrastructure environment name'
        type: string
        default: $DEFAULT_ENV
      region:
        description: 'aws region'
        type: string
        default: $DEFAULT_REGION
    steps:
      - setup-job
      - setup-backend:
          account: << parameters.account >>
          env: << parameters.env >>
          region: << parameters.region >>

workflows:
  aws-bootstrap-pipeline:
    jobs:
      - terraform-plan:
          name: TEST plan
          account: sandbox
          env: test
      - approve:
          name: TEST approve
          type: approval
          requires:
          - TEST plan
      - terraform-apply:
          name: TEST apply
          account: sandbox
          env: test
          requires:
            - TEST approve
      - terraform-plan:
          name: RUN plan
          account: sandbox
          env: run
          requires:
            - TEST apply
      - approve:
          name: RUN approve
          type: approval
          requires:
            - RUN plan
      - terraform-apply:
          name: RUN apply
          account: sandbox
          env: run
          requires:
            - RUN approve
