---
version: 2.1

executors:

  bootstrap-cluster:
    working_directory: ~/aws-bootstrap
    docker:
    - image: quay.io/feedyard/circleci-infra-agent
    environment:
      BASH_ENV: local.env
      PREFIX: feedyard
      TEST_ACCOUNT: sandbox
      RUN_ACCOUNT: sandbox

commands:

  setup-job:
    steps:
    - checkout
    - setup_remote_docker
    - run:
        name: confirm Docker engine running
        command: docker info
    - run:
        name: decrypt secrets
        command: invoke dec

  # input params
  # 1 = s3 bucket name, this version of the script imposes the '-tf-state' name ending requirement
  # 2 = bucket key, or folder path and filename for tf state file
  # 3 = aws region
  # 4 = ~/.aws/credentials profile to use

  setup-backend:
    parameters:
      bucket:
        description: 's3 bucket name prefix and account - the shell script will format as <prefix>-<account>-tf-state'
        type: string
    steps:
    - run:
        name: put parameter to stdout
        command: echo << parameters.bucket >>

jobs:

  terraform-plan:
    executor: bootstrap-cluster
    parameters:
      prefix:
        description: 'prefix'
        type: string
      account:
        description: 'prefix'
        type: string
    steps:
      - setup-job
      - setup-backend:
          bucket: << parameters.prefix >>-<< parameters.account >>

  terraform-apply:
    executor: bootstrap-cluster
    parameters:
      prefix:
        description: 'prefix'
        type: string
      account:
        description: 'short name used to identify aws account. e.g., sandbox, prod'
        type: string
    steps:
    - setup-job
    - setup-backend:
        bucket: << parameters.prefix >>-<< parameters.account >>

workflows:
  aws-bootstrap-cluster-pipeline:
    jobs:
      - terraform-plan:
          name: TEST plan
          prefix: $PREFIX
          account: $TEST_ACCOUNT
      - approve:
          name: TEST approve
          type: approval
          requires:
          - TEST plan
      - terraform-apply:
          name: TEST apply
          prefix: $PREFIX
          account: $TEST_ACCOUNT
          requires:
            - TEST approve
      - terraform-plan:
          name: RUN plan
          prefix: $PREFIX
          account: $RUN_ACCOUNT
          requires:
            - TEST apply
      - approve:
          name: RUN approve
          type: approval
          requires:
            - RUN plan
      - terraform-apply:
          name: RUN apply
          prefix: $PREFIX
          account: $RUN_ACCOUNT
          requires:
            - RUN approve
